---
kind: pipeline
type: docker
name: default
 
steps:
- name: build
  image: golang
  environment:
    A_SECRET:
      from_secret: a_secret
  commands:
  - echo $$A_SECRET
  - go run . > test_secret.txt
  - cat test_secret.txt
